title: mspi
emails:
  - mspi21@protonmail.com
  - milan.spinka@fit.cvut.cz
description: >- # this means to ignore newlines until "baseurl:"
  information security & security research nerd.
baseurl: ""
url: "https://www.mspi.eu"
github_username: mspi21
linkedin_username: mspi21

# Global variables :evilvagner:
show_excerpts: true

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
